
- name: Update package cache
  apk:
      update_cache: yes
- name: Upgrade all packages
  apk:
      available: yes
      upgrade: yes

- name: Install iptables
  apk:
      name: iptables
      state: present

- name: Install ip6tables
  apk:
      name: ip6tables
      state: present

- name: Install dhcpcd
  apk:
      name: dhcpcd
      state: present

- name: Install dhcpcd-doc
  apk:
      name: dhcpcd-doc
      state: present

- name: Install radvd
  apk:
      name: radvd
      state: present

- name: Install Unbound DNS resolver
  apk:
      name: unbound
      state: present

- name: Install Haveged
  apk:
      name: haveged
      state: present

- name: Install OpenVPN
  apk:
      name: openvpn
      state: present

- name: Install iputils
  apk:
      name: iputils
      state: present

- name: Install iproute2
  apk:
      name: iproute2
      state: present

- name: Install easy-rsa
  apk:
      name: easy-rsa
      state: present

- name: Install file
  apk:
      name: file
      state: present

- name: Enable haveged service
  service:
      name: haveged
      state: started
      enabled: yes
