---
- hosts: hades
  remote_user: root

  roles:
      - hostname
      - resolv
      - repositories
      - packages
      - sysctl
      - network
      - chrony
      #- firewall
      - unbound
      - dnscrypt
