- name: Install chrony
  yum:
      name: chrony
      state: present

- name: Copy chrony config file
  copy: src=chrony.conf dest=/etc/chrony.conf mode=0644

- name: Enable and start chronyd service
  systemd:
      name: chronyd
      state: started
      enabled: yes
