- name: Copy named config file
  copy: src=named.conf dest=/etc/named.conf mode=0640

- file:
    path: /etc/named/zones
    state: directory
    mode: 0755

- name: Copy forward zone config file
  copy: src=db.zeus.as.home dest=/etc/named/zones/db.zeus.as.home mode=0640

- name: Copy reverse zone config file
  copy: src=db.192.168.1 dest=/etc/named/zones/db.192.168.1 mode=0640
