- name: Generate /etc/ssh/ RSA host key
  command: ssh-keygen -q -b 4096 -t rsa -f /root/.ssh/id_rsa -C "" -N ""
  args:
    creates: /root/.ssh/id_rsa

- name: Copy ssh keys to hades
  shell: sshpass -p test1234 ssh-copy-id -i /root/.ssh/id_rsa.pub root@192.168.2.1

- name: Copy ssh keys to zeus
  shell: sshpass -p test1234 ssh-copy-id -i /root/.ssh/id_rsa.pub root@192.168.1.22
