- name: Copy iptables rules
  copy: src=iptables.rules dest=/etc/iptables/iptables.rules mode=0700

- name: Mangle table PREROUTING ACCEPT
  iptables:
      table: mangle
      chain: PREROUTING
      jump: ACCEPT

- name: Mangle table INPUT ACCEPT
  iptables:
      table: mangle
      chain: INPUT
      jump: ACCEPT

- name: Mangle table FORWARD ACCEPT
  iptables:
      table: mangle
      chain: FORWARD
      jump: ACCEPT

- name: Mangle table OUTPUT ACCEPT
  iptables:
      table: mangle
      chain: OUTPUT
      jump: ACCEPT

- name: Mangle table POSTROUTING ACCEPT
  iptables:
      table: mangle
      chain: POSTROUTING
      jump: ACCEPT

- name: Filter table INPUT ACCEPT
  iptables:
      table: filter
      chain: INPUT
      jump: ACCEPT

- name: Allows hosts of the network to use WAN connection
  iptables:
      table: nat
      chain: POSTROUTING
      source: 192.168.1.0/24
      out_interface: eth0
      jump: MASQUERADE

- name: Restart iptables service
  service:
      name: iptables
      state: restarted
      enabled: yes
