- name: Copy unbound config
  copy: src=unbound.conf dest=/etc/unbound/unbound.conf mode=0700

- name: Restart unbound service
  service:
      name: unbound
      state: restarted
      enabled: yes
