- name: Remove enp0s3 from public zone
  command: firewall-cmd --zone=public --remove-interface=enp0s3 --permanent

- name: Remove enp0s8 from public zone
  command: firewall-cmd --zone=public --remove-interface=enp0s8 --permanent

- name: Remove enp0s9 from public zone
  command: firewall-cmd --zone=public --remove-interface=enp0s9 --permanent

- name: Remove enp0s10 from public zone
  command: firewall-cmd --zone=public --remove-interface=enp0s10 --permanent

- name: Change enp0s3 zone to external
  command: firewall-cmd --zone=external --change-interface=enp0s8 --permanent

- name: Change enp0s8 zone to dmz
  command: firewall-cmd --zone=dmz --change-interface=enp0s8 --permanent

- name: Change enp0s9 zone to work
  command: firewall-cmd --zone=work --change-interface=enp0s9 --permanent

- name: Change enp0s10 zone to home
  command: firewall-cmd --zone=home --change-interface=enp0s10 --permanent

- name: Add subnet 192.168.1.0 to DMZ zone
  command: firewall-cmd --zone=dmz --add-source=192.168.1.0/24 --permanent

- name: Add subnet 192.168.2.0 to work zone
  command: firewall-cmd --zone=work --add-source=192.168.2.0/24 --permanent

- name: Add subnet 192.168.3.0 to home zone
  command: firewall-cmd --zone=home --add-source=192.168.3.0/24 --permanent

- name: Allow DHCP in DMZ
  command: firewall-cmd --zone=dmz --add-service=dhcp --permanent

- name: Allow DNS in DMZ
  command: firewall-cmd --zone=dmz --add-service=dns --permanent

- name: Allow FTP in DMZ
  command: firewall-cmd --zone=dmz --add-service=ftp --permanent

- name: Allow HTTP in DMZ
  command: firewall-cmd --zone=dmz --add-service=http --permanent

- name: Allow DHCP in work
  command: firewall-cmd --zone=work --add-service=dhcp --permanent

- name: Allow Wireguard VPN service on port 51820
  command: firewall-cmd --zone=external --add-port=51820/udp --permanent

- name: Forward packets from external port 80 to web server
  command: firewall-cmd --zone=external --add-forward-port=port=80:proto=tcp:toport=80:toaddr=192.168.1.21 --permanent

- name: Forward packets from external port 443 to web server
  command: firewall-cmd --zone=external --add-forward-port=port=443:proto=tcp:toport=443:toaddr=192.168.1.21 --permanent

- name: Reload firewall
  command: firewall-cmd --reload
