
- name: Update package cache and upgrade packages
  yum:
      update_cache: yes
      update_only: yes

- name: Install bind dns server
  yum:
      name: bind
      state: present

- name: Install bind-utils
  yum:
      name: bind-utils
      state: present

- name: Install vim
  yum:
      name: vim
      state: present
