- name: Enable OpenVPN service
  service:
      name: openvpn
      state: started
      enabled: yes

- name: Copy /etc/openvpn/openvpn.conf
  copy: src=openvpn.conf dest=/etc/openvpn/openvpn.conf mode=0755

- name: Create directory for keys
  file: path=/etc/openvpn/keys state=directory

- name: Copy /usr/share/easy-rsa/vars
  copy: src=vars dest=/usr/share/easy-rsa/vars mode=0755

- name: Execute the easyrsa init-pki
  command: sh /usr/share/easy-rsa/easyrsa init-pki
  args:
      chdir: /usr/share/easy-rsa

- name: Execute the easyrsa build-ca nopass
  command: sh /usr/share/easy-rsa/easyrsa build-ca nopass
  args:
      chdir: /usr/share/easy-rsa
      creates: /etc/openvpn/keys/ca.crt
